FROM library/alpine:latest

#system
ARG TZ="Asia/Shanghai"

ENV TZ ${TZ}
ENV ROOT_PASSWORD=root
ENV HTTP_USER=sakuya

#nomal setup
RUN set -ex \
    && apk --no-cache upgrade \
    && apk add --no-cache --virtual .build-deps ca-certificates tzdata openssh \
    squid nghttp2 \
    python3 py3-numpy py3-pillow libwebp py3-yaml py3-requests python3-dev \
    libffi-dev musl-dev openssl-dev gcc ffmpeg libmagic \
    && ln -sf /usr/share/zoneinfo/${TZ} /etc/localtime \
    && echo ${TZ} > /etc/timezone \
    && mkdir -p /var/run/sshd \
    && sed -ri s/#PermitRootLogin.*/PermitRootLogin\ yes/ /etc/ssh/sshd_config \
    && sed -ri 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_config \
    && echo "root:${ROOT_PASSWORD}" | chpasswd \
    && htpasswd -b -c /etc/squid/password ${HTTP_USER} ${ROOT_PASSWORD} \
    
#install v2ray
ENV V2RAY_LOG_DIR=/var/log/v2ray
ENV V2RAY_CONFIG_DIR=/etc/v2ray/
ENV V2RAY_VERSION=v3.39
ENV V2RAY_DOWNLOAD_URL=https://github.com/v2ray/v2ray-core/releases/download/${V2RAY_VERSION}/v2ray-linux-64.zip

RUN mkdir -p /tmp/v2ray \
    && wget -O /tmp/v2ray/v2ray.zip ${V2RAY_DOWNLOAD_URL} \
    && unzip /tmp/v2ray/v2ray.zip -d /tmp/v2ray/ \
    && mv /tmp/v2ray/v2ray-${V2RAY_VERSION}-linux-64/v2ray /usr/bin \
    && chmod +x /usr/bin/v2ray 
    
#install efb
RUN set -ex \
    && pip3 install --upgrade pip \
    && pip3 install --no-cache-dir ehforwarderbot \
    && pip3 install --no-cache-dir efb-telegram-master \
    && pip3 install --no-cache-dir efb-wechat-slave \
    && mkdir -p /root/.ehforwarderbot/profiles/default/ \
    && mkdir -p /root/.ehforwarderbot/profiles/default/blueset.telegram \ 
    && mkdir -p /root/.ehforwarderbot/profiles/default/blueset.wechat \
    
#make clean
    && apk del .build-deps \
    && rm -rf /tmp/* /var/cache/apk/* /root/.cache/*

#copy config file
COPY nghttpx.conf /etc/nghttpx/nghttpx.conf
COPY squid.conf /etc/squid/squid.conf
COPY blueset.telegram-config.yaml /root/.ehforwarderbot/profiles/default/blueset.telegram/config.yaml
COPY default-config.yaml /root/.ehforwarderbot/profiles/default/config.yaml
COPY v2rayconfig.json /etc/v2ray/config.json
COPY entrypoint.sh /usr/local/bin/entrypoint.sh

#ss
ENV SS_PORT=1343
ENV SS_PASSWORD=sakuya
ENV SS_METHOD=aes-256-gcm

#vmess
ENV VMESS_PORT=5061
ENV VMESS_ID=00000000-0000-0000-0000-000000000000
ENV VMESS_LEVEL=1
ENV VMESS_ALTERID=64

#kcp
ENV KCP_PORT_VMESS=5061
ENV KCP_MUT=1350
ENV KCP_TTI=50
ENV KCP_UPLINK=5
ENV KCP_DOWNLINK=120
ENV KCP_READBUFF=2
ENV KCP_WRITEBUFF=2

#EFB
ENV TOKEN=88888888:00000000000000000
ENV ADM=999999999

#http proxy
ENV HTTP_USER=sakuya
ENV SERVER_CRT=none
ENV SERVER_KEY=none

EXPOSE ${SS_PORT}/tcp
EXPOSE ${SS_PORT}/udp
EXPOSE ${VMESS_PORT}/tcp
EXPOSE ${KCP_PORT_VMESS}/udp
EXPOSE 22/tcp
EXPOSE 2043/tcp

ENTRYPOINT [ "bash", "/usr/local/bin/entrypoint.sh" ]
